// examples/react-example.tsx
/**
 * React Example - Pay2Nature Widget
 * 
 * Usage:
 * 1. Install: npm install @pay2nature/widget-sdk
 * 2. Import the component
 * 3. Use in your React app
 */

import React, { useState } from 'react';
import { Pay2NatureWidgetComponent, ContributionData } from '@pay2nature/widget-sdk';

function App() {
  const [contributionData, setContributionData] = useState<ContributionData | null>(null);

  return (
    <div style={{ maxWidth: '800px', margin: '50px auto', padding: '20px' }}>
      <h1>Pay2Nature Widget - React Example</h1>
      
      {contributionData && (
        <div style={{ 
          padding: '15px', 
          backgroundColor: '#d1fae5', 
          borderRadius: '8px',
          marginBottom: '20px'
        }}>
          <h3>Thank you for your contribution!</h3>
          <p>Amount: {contributionData.currency}{contributionData.amount}</p>
          {contributionData.paymentUrl && (
            <p>Payment URL: <a href={contributionData.paymentUrl} target="_blank" rel="noopener noreferrer">Open Payment</a></p>
          )}
        </div>
      )}

      <Pay2NatureWidgetComponent
        widgetToken={process.env.REACT_APP_WIDGET_TOKEN || 'your-widget-token'}
        baseUrl={process.env.REACT_APP_API_URL || 'https://api.pay2nature.com'}
        onContribution={(data) => {
          console.log('Contribution made:', data);
          setContributionData(data);
        }}
        onError={(error) => {
          console.error('Widget error:', error);
          alert('An error occurred: ' + error.message);
        }}
        style={{ marginTop: '20px' }}
      />
    </div>
  );
}

export default App;

// examples/vue-example.vue
<template>
  <div class="app">
    <h1>Pay2Nature Widget - Vue.js Example</h1>
    
    <div v-if="contributionData" class="success-message">
      <h3>Thank you for your contribution!</h3>
      <p>Amount: {{ contributionData.currency }}{{ contributionData.amount }}</p>
      <p v-if="contributionData.paymentUrl">
        <a :href="contributionData.paymentUrl" target="_blank" rel="noopener noreferrer">
          Open Payment
        </a>
      </p>
    </div>

    <Pay2NatureWidget
      :widget-token="widgetToken"
      :base-url="baseUrl"
      @contribution="handleContribution"
      @error="handleError"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import Pay2NatureWidget from '@pay2nature/widget-sdk/vue/Pay2NatureWidget.vue';
import type { ContributionData } from '@pay2nature/widget-sdk';

const widgetToken = ref(import.meta.env.VITE_WIDGET_TOKEN || 'your-widget-token');
const baseUrl = ref(import.meta.env.VITE_API_URL || 'https://api.pay2nature.com');
const contributionData = ref<ContributionData | null>(null);

const handleContribution = (data: ContributionData) => {
  console.log('Contribution made:', data);
  contributionData.value = data;
};

const handleError = (error: Error) => {
  console.error('Widget error:', error);
  alert('An error occurred: ' + error.message);
};
</script>

<style scoped>
.app {
  max-width: 800px;
  margin: 50px auto;
  padding: 20px;
}

.success-message {
  padding: 15px;
  background-color: #d1fae5;
  border-radius: 8px;
  margin-bottom: 20px;
}
</style>
