// examples/nextjs-example.tsx
/**
 * Next.js Example - Pay2Nature Widget
 * 
 * For Next.js 13+ App Router, use 'use client' directive
 * For Pages Router, this works as-is
 */

'use client'; // Required for Next.js 13+ App Router

import { Pay2NatureWidgetComponent, ContributionData } from '@pay2nature/widget-sdk';
import { useState } from 'react';

export default function DonationPage() {
  const [contributionData, setContributionData] = useState<ContributionData | null>(null);

  return (
    <div style={{ maxWidth: '800px', margin: '50px auto', padding: '20px' }}>
      <h1>Support Nature Conservation</h1>
      <p>Make a contribution to verified nature projects.</p>

      {contributionData && (
        <div style={{ 
          padding: '15px', 
          backgroundColor: '#d1fae5', 
          borderRadius: '8px',
          marginBottom: '20px'
        }}>
          <h3>Thank you for your contribution!</h3>
          <p>Amount: {contributionData.currency}{contributionData.amount}</p>
        </div>
      )}

      <Pay2NatureWidgetComponent
        widgetToken={process.env.NEXT_PUBLIC_WIDGET_TOKEN!}
        baseUrl={process.env.NEXT_PUBLIC_API_URL!}
        onContribution={(data) => {
          console.log('Contribution made:', data);
          setContributionData(data);
        }}
        onError={(error) => {
          console.error('Widget error:', error);
        }}
      />
    </div>
  );
}

/**
 * Alternative: Server-Side Rendering (SSR) with dynamic import
 * Use this if you need SSR or want to avoid client-side bundle
 */

// import dynamic from 'next/dynamic';
// 
// const Pay2NatureWidget = dynamic(
//   () => import('@pay2nature/widget-sdk').then(mod => mod.Pay2NatureWidgetComponent),
//   { ssr: false }
// );
// 
// export default function DonationPage() {
//   return (
//     <div>
//       <Pay2NatureWidget
//         widgetToken={process.env.NEXT_PUBLIC_WIDGET_TOKEN!}
//         baseUrl={process.env.NEXT_PUBLIC_API_URL!}
//       />
//     </div>
//   );
// }

// examples/vue-example.vue
<template>
  <div class="app">
    <h1>Pay2Nature Widget - Vue.js Example</h1>
    
    <div v-if="contributionData" class="success-message">
      <h3>Thank you for your contribution!</h3>
      <p>Amount: {{ contributionData.currency }}{{ contributionData.amount }}</p>
      <p v-if="contributionData.paymentUrl">
        <a :href="contributionData.paymentUrl" target="_blank" rel="noopener noreferrer">
          Open Payment
        </a>
      </p>
    </div>

    <Pay2NatureWidget
      :widget-token="widgetToken"
      :base-url="baseUrl"
      @contribution="handleContribution"
      @error="handleError"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import Pay2NatureWidget from '@pay2nature/widget-sdk/vue/Pay2NatureWidget.vue';
import type { ContributionData } from '@pay2nature/widget-sdk';

const widgetToken = ref(import.meta.env.VITE_WIDGET_TOKEN || 'your-widget-token');
const baseUrl = ref(import.meta.env.VITE_API_URL || 'https://api.pay2nature.com');
const contributionData = ref<ContributionData | null>(null);

const handleContribution = (data: ContributionData) => {
  console.log('Contribution made:', data);
  contributionData.value = data;
};

const handleError = (error: Error) => {
  console.error('Widget error:', error);
  alert('An error occurred: ' + error.message);
};
</script>

<style scoped>
.app {
  max-width: 800px;
  margin: 50px auto;
  padding: 20px;
}

.success-message {
  padding: 15px;
  background-color: #d1fae5;
  border-radius: 8px;
  margin-bottom: 20px;
}
</style>
