// src/vue/Pay2NatureWidget.vue
<template>
  <div :id="effectiveContainerId" ref="containerRef" :class="className" :style="style"></div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onMounted, onBeforeUnmount, watch, type WatchStopHandle } from 'vue';
import { Pay2NatureWidget, Pay2NatureWidgetOptions, ContributionData } from '../core/Pay2NatureWidget';

// Module-level counter for generating unique fallback container IDs across
// multiple `<Pay2NatureWidget>` instances on the same page.
let p2nInstanceCounter = 0;

export default defineComponent({
  name: 'Pay2NatureWidget',
  props: {
    widgetToken: {
      type: String,
      required: true,
    },
    baseUrl: {
      type: String,
      required: true,
    },
    /**
     * Container element id. If omitted, a unique id is generated automatically
     * so multiple instances on the same page do not collide.
     */
    containerId: {
      type: String,
      default: undefined,
    },
    onContribution: {
      type: Function as () => (data: ContributionData) => void,
      default: undefined,
    },
    onToggle: {
      type: Function as () => (isEnabled: boolean) => void,
      default: undefined,
    },
    onError: {
      type: Function as () => (error: Error) => void,
      default: undefined,
    },
    className: {
      type: String,
      default: '',
    },
    style: {
      type: [String, Object] as unknown as () => string | Record<string, string | number>,
      default: () => ({}),
    },
  },
  emits: ['contribution', 'error', 'toggle'],
  setup(props, { emit }) {
    const containerRef = ref<HTMLElement | null>(null);
    const fallbackContainerId = `pay2nature-widget-${++p2nInstanceCounter}`;
    const effectiveContainerId = computed(() => props.containerId ?? fallbackContainerId);
    let widgetInstance: Pay2NatureWidget | null = null;
    const watchStops: WatchStopHandle[] = [];

    const initializeWidget = () => {
      if (!containerRef.value) return;

      const options: Pay2NatureWidgetOptions = {
        widgetToken: props.widgetToken,
        baseUrl: props.baseUrl,
        container: containerRef.value,
        onContribution: (data) => {
          props.onContribution?.(data);
          emit('contribution', data);
        },
        onError: (error) => {
          props.onError?.(error);
          emit('error', error);
        },
        onToggle: (isEnabled) => {
          props.onToggle?.(isEnabled);
          emit('toggle', isEnabled);
        },
      };

      widgetInstance = new Pay2NatureWidget(options);
    };

    const reinitialize = () => {
      if (widgetInstance) {
        widgetInstance.destroy();
        widgetInstance = null;
      }
      initializeWidget();
    };

    onMounted(() => {
      initializeWidget();
      // Watch each prop separately to avoid the new-array-each-tick inefficiency
      // and to allow per-prop cleanup on unmount.
      watchStops.push(watch(() => props.widgetToken, reinitialize));
      watchStops.push(watch(() => props.baseUrl, reinitialize));
    });

    onBeforeUnmount(() => {
      for (const stop of watchStops) stop();
      watchStops.length = 0;
      if (widgetInstance) {
        widgetInstance.destroy();
        widgetInstance = null;
      }
    });

    return {
      containerRef,
      effectiveContainerId,
    };
  },
});
</script>

// src/react/Pay2NatureWidget.tsx
/**
 * React Component Wrapper for Pay2Nature Widget
 */

import React, { useEffect, useRef } from 'react';
import { Pay2NatureWidget, Pay2NatureWidgetOptions, ContributionData } from '../core/Pay2NatureWidget';

export interface Pay2NatureWidgetProps {
  widgetToken: string;
  baseUrl: string;
  /**
   * Container element id. If omitted, a unique id is generated automatically
   * so multiple `<Pay2NatureWidgetComponent>` instances on the same page do
   * not collide. Override only when you need a stable selector for your own
   * styling or testing hooks.
   */
  containerId?: string;
  onContribution?: (data: ContributionData) => void;
  onToggle?: (isEnabled: boolean) => void;
  onError?: (error: Error) => void;
  className?: string;
  style?: React.CSSProperties;
}

// Module-level counter for generating unique fallback container IDs.
// Works in React 16.8+ (cannot use React 18's useId because the SDK supports older versions).
let p2nInstanceCounter = 0;

export const Pay2NatureWidgetComponent: React.FC<Pay2NatureWidgetProps> = ({
  widgetToken,
  baseUrl,
  containerId,
  onContribution,
  onToggle,
  onError,
  className,
  style,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const fallbackIdRef = useRef<string | null>(null);
  if (fallbackIdRef.current === null) {
    fallbackIdRef.current = `pay2nature-widget-${++p2nInstanceCounter}`;
  }
  const effectiveContainerId = containerId ?? fallbackIdRef.current;
  const widgetInstanceRef = useRef<Pay2NatureWidget | null>(null);
  const callbacksRef = useRef({ onContribution, onToggle, onError });

  // Update callbacks ref when they change (without causing re-initialization)
  useEffect(() => {
    callbacksRef.current = { onContribution, onToggle, onError };
  }, [onContribution, onToggle, onError]);

  useEffect(() => {
    if (!containerRef.current) return;

    // Destroy existing instance if it exists
    if (widgetInstanceRef.current) {
      widgetInstanceRef.current.destroy();
      widgetInstanceRef.current = null;
    }

    const options: Pay2NatureWidgetOptions = {
      widgetToken,
      baseUrl,
      container: containerRef.current,
      onContribution: (data) => callbacksRef.current.onContribution?.(data),
      onToggle: (isEnabled) => callbacksRef.current.onToggle?.(isEnabled),
      onError: (error) => callbacksRef.current.onError?.(error),
    };

    widgetInstanceRef.current = new Pay2NatureWidget(options);

    return () => {
      if (widgetInstanceRef.current) {
        widgetInstanceRef.current.destroy();
        widgetInstanceRef.current = null;
      }
    };
  }, [widgetToken, baseUrl]); // Only re-initialize when token or baseUrl changes

  return (
    <div
      id={effectiveContainerId}
      ref={containerRef}
      className={className}
      style={style}
    />
  );
};

Pay2NatureWidgetComponent.displayName = 'Pay2NatureWidgetComponent';

export default Pay2NatureWidgetComponent;
